import os
import duckdb
import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt
import contextily as cx
from shapely.geometry import Point
import pyogrio

# Configuration
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
OSM_DB = os.path.join(BASE_DIR, "../../data/03_interim/osm_analysis.db")
HIGHWAY_GPKG = os.path.join(BASE_DIR, "../../data/03_interim/highway_traffic.gpkg")
OUTPUT_GPKG = os.path.join(BASE_DIR, "../../data/03_interim/mapped_ramps.gpkg")
VERIFICATION_PLOT = os.path.join(BASE_DIR, "../../data/plots/highway_traffic_maps/ramp_mapping_verification.png")

def load_osm_ramps():
    """Extract all motorway_link and trunk_link nodes from OSM as points."""
    print("Connecting to OSM DuckDB to extract ramps...")
    con = duckdb.connect(OSM_DB, read_only=True)
    con.execute("INSTALL spatial; LOAD spatial;")
    
    # We take the centroid of the link to represent the entry point
    # We also keep it in EPSG:3035 (which is the native CRS in OSM_DB)
    q_ramps = """
        SELECT 
            id as osm_id,
            highway,
            ST_X(ST_Centroid(geometry)) as x,
            ST_Y(ST_Centroid(geometry)) as y
        FROM roads_global
        WHERE highway IN ('motorway_link', 'trunk_link')
    """
    df_ramps = con.execute(q_ramps).df()
    con.close()
    
    if df_ramps.empty:
        raise ValueError("No ramps found in OSM database!")
        
    print(f"Extracted {len(df_ramps)} ramps.")
    
    # Convert to GeoDataFrame
    geometry = [Point(xy) for xy in zip(df_ramps.x, df_ramps.y)]
    gdf_ramps = gpd.GeoDataFrame(df_ramps, geometry=geometry, crs="EPSG:3035")
    return gdf_ramps

def load_all_highways():
    """Load all highway layers from the GPKG into one GeoDataFrame."""
    print("Loading highway traffic segments...")
    layers = pyogrio.list_layers(HIGHWAY_GPKG)
    
    gdfs = []
    for layer_name, _ in layers:
        gdf = gpd.read_file(HIGHWAY_GPKG, layer=layer_name)
        gdfs.append(gdf)
        
    all_highways = pd.concat(gdfs, ignore_index=True)
    
    # Ensure it's in the same projection as the ramps (EPSG:3035 for accurate distance mapping)
    if all_highways.crs != "EPSG:3035":
        all_highways = all_highways.to_crs("EPSG:3035")
        
    print(f"Loaded {len(all_highways)} highway segments from {len(layers)} highways.")
    return all_highways

def map_ramps_to_highways(gdf_ramps, all_highways):
    """Spatially join ramps to the physically closest highway segment."""
    print("Performing spatial join (snapping ramps to nearest highway segment)...")
    
    # We use sjoin_nearest. 
    # max_distance is in meters (EPSG:3035 is a metric projection). 
    # If a link is further than 2000m from a highway, it might be a mapping error or irrelevant.
    mapped_ramps = gpd.sjoin_nearest(
        gdf_ramps, 
        all_highways, 
        how="inner", 
        max_distance=2000, 
        distance_col="dist_to_highway_m"
    )
    
    print(f"Successfully mapped {len(mapped_ramps)} ramps.")
    return mapped_ramps

def generate_verification_plot(mapped_ramps, all_highways):
    """Plot the highways and color the ramps by their matched highway."""
    print("Generating verification plot...")
    os.makedirs(os.path.dirname(VERIFICATION_PLOT), exist_ok=True)
    
    # Reproject to Web Mercator for Contextily basemap
    ramps_plot = mapped_ramps.to_crs(epsg=3857)
    highways_plot = all_highways.to_crs(epsg=3857)
    
    fig, ax = plt.subplots(figsize=(15, 15))
    
    # Plot highways as thick grey lines
    highways_plot.plot(ax=ax, color='gray', linewidth=3, alpha=0.6, label='Highways')
    
    # Plot ramps, colored by the highway they matched with
    # We use a categorical colormap
    ramps_plot.plot(
        ax=ax, 
        column='highway_right', # 'highway_right' is the column name from the sjoin (the highway name)
        cmap='tab20', 
        markersize=15, 
        legend=True,
        legend_kwds={'bbox_to_anchor': (1, 1), 'loc': 'upper left'}
    )
    
    ax.set_title("Verification: Ramps Mapped to Highways", fontsize=16)
    ax.set_axis_off()
    
    cx.add_basemap(ax, source=cx.providers.CartoDB.Positron)
    
    plt.tight_layout()
    plt.savefig(VERIFICATION_PLOT, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Plot saved to {VERIFICATION_PLOT}")

def main():
    gdf_ramps = load_osm_ramps()
    all_highways = load_all_highways()
    
    mapped_ramps = map_ramps_to_highways(gdf_ramps, all_highways)
    
    generate_verification_plot(mapped_ramps, all_highways)
    
    print(f"Saving mapped ramps to {OUTPUT_GPKG}...")
    # Drop index column generated by sjoin
    if 'index_right' in mapped_ramps.columns:
        mapped_ramps = mapped_ramps.drop(columns=['index_right'])
        
    mapped_ramps.to_file(OUTPUT_GPKG, driver="GPKG")
    print("Step 1 Complete.")

if __name__ == "__main__":
    main()
